language: java
install: true

before_script:
  - bin/ci-setup-env.sh

script:
  - ./gradlew build

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew publish bintrayUpload
    on:
      tags: true
